# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: sdl/postgres:latest_ru
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./../pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080